name: mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  font_awesome_flutter: 8.8.1

  firebase_storage: 3.1.5
  firebase_auth: 0.16.0
  google_sign_in: 4.4.4
  cloud_firestore: ^0.13.5
  rxdart: 0.21.0
  flutter_signin_button: ^1.0.0

  flutter_dialogflow: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bot.png
    - assets/myphoto.png
    - assets/chatbot.json
