name: Vera
description: Chat Bot - Vera.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  font_awesome_flutter: 8.8.1
  flutter_svg: 0.17.4
  flutter_launcher_icons: "^0.6.1"

  flutter_mobx: 1.1.0
  provider: 4.0.5+1
  mobx: ^1.0.0

  firebase_storage: 3.1.5
  firebase_auth: 0.16.0
  google_sign_in: 4.4.4
  cloud_firestore: ^0.13.5
  rxdart: 0.21.0
  flutter_dialogflow: ^0.1.1

dev_dependencies:
  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/vera-bot.png
    - assets/vtex.svg
    - assets/login-vera.png
    - assets/chatbot.json
    - assets/vera.png
